services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
      # จับคู่ ซ้ายเครื่องเรา ขวา docker
    volumes:
      - "./server:/app"
      - "/app/node_modules"
      # postgresql is potocal
      # postgres username
      # postgres password
      # บอก location host @db: ชื่อที่เก็บ database ไว้ที่ port 5432
      # app_db ชื่อ database
    command: nodemon --legacy-watch index.js
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
      - HOST=db
      - USER=postgres
      - PASSWORD=postgres
      - DB=app_db
      - DB_PORT=5432
      - SERVER_PORT=5000
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
      # จับคู่ ซ้ายเครื่องเรา ขวา docker
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    # share แค่ภายใน
    volumes:
      # ซ้าย เครื่องเรา ขวา server
      # ถ้ามี folder ./pgdata:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
# share ภายนอกทุก service
volumes:
  pgdata:
